version: '3.2'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      args:
        - USER_ID
        - GROUP_ID
    container_name: weatherforecast-php
    volumes:
        - ./:/var/www/html